import {
  SlashCommandBuilder,
  ChatInputCommandInteraction,
  PermissionFlagsBits,
  EmbedBuilder,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  TextChannel,
  ChannelType
} from 'discord.js';
import OrdersService from '../../../services/OrdersService';

export default {
  data: new SlashCommandBuilder()
    .setName('orders-setup')
    .setDescription('Configurar o sistema de encomendas automaticamente detectando canais da categoria')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  cooldown: 5, // 5 second cooldown to prevent accidental double execution

  async execute(interaction: ChatInputCommandInteraction) {
    try {
      // Get the channel where the command was run
      const channel = interaction.channel;

      if (!channel || !(channel instanceof TextChannel)) {
        await interaction.reply({
          content: '❌ Este comando deve ser executado em um canal de texto.',
          ephemeral: true
        });
        return;
      }

      // Check if channel has a parent category
      if (!channel.parent || channel.parent.type !== ChannelType.GuildCategory) {
        await interaction.reply({
          content: '❌ Este canal deve estar dentro de uma categoria.\n\n**Como configurar:**\n1. Crie uma categoria (ex: "Encomendas")\n2. Crie canais para suas firmas (ex: fazenda, berçário, armaria)\n3. Crie um canal "fazer-encomendas" onde este comando será executado\n4. Execute este comando no canal "fazer-encomendas"',
          ephemeral: true
        });
        return;
      }

      const guildId = interaction.guildId;
      if (!guildId) {
        await interaction.reply({
          content: '❌ Erro ao obter ID do servidor.',
          ephemeral: true
        });
        return;
      }

      const category = channel.parent;

      // Get all text channels in the category (excluding the command channel)
      const firmChannels = Array.from(category.children.cache.values())
        .filter(ch =>
          ch.type === ChannelType.GuildText &&
          ch.id !== channel.id &&
          ch instanceof TextChannel
        ) as TextChannel[];

      if (firmChannels.length === 0) {
        await interaction.reply({
          content: '⚠️ Nenhum canal detectado na categoria para criar firmas.\n\n**Certifique-se de:**\n1. Criar canais de texto na categoria (ex: fazenda, berçário, armaria)\n2. Os canais devem estar na mesma categoria deste canal\n3. Execute o comando novamente após criar os canais',
          ephemeral: true
        });
        return;
      }

      // Auto-generate firm configs from detected channels
      const autoGeneratedFirms = firmChannels.map((firmChannel, index) => ({
        id: firmChannel.id,
        name: firmChannel.name,
        description: `Encomendas para ${firmChannel.name}`,
        discordRoleIds: [],
        discordRoleNames: [],
        supplierUserIds: [],
        supplierUserNames: [],
        items: [],
        notificationChannelId: firmChannel.id,
        active: true,
        order: index
      }));

      // Get or create config
      let config = await OrdersService.getConfig(guildId);
      if (!config) {
        // Create new config with auto-generated firms
        config = {
          configId: 'orders_config',
          firms: autoGeneratedFirms,
          settings: {
            orderChannelId: channel.id,
            notificationsEnabled: true,
            dmNotificationsEnabled: true,
            requireApproval: false,
            maxActiveOrdersPerUser: 5,
            orderCooldownMinutes: 0,
            embedColor: '#00FF00'
          },
          command: {
            name: 'encomenda',
            description: 'Fazer uma encomenda para outro jogador',
            permissions: 'SendMessages'
          },
          messages: {
            orderPlaced: '✅ **Encomenda Realizada!**\n\n{customerName} encomendou {quantity}x {item} de {supplierName}',
            orderAccepted: '✅ Sua encomenda foi aceita por {supplierName}!',
            orderRejected: '❌ Sua encomenda foi rejeitada por {supplierName}.\nMotivo: {reason}',
            orderCompleted: '🎉 Sua encomenda foi concluída por {supplierName}!',
            orderCancelled: '❌ Encomenda cancelada.',
            dmNotificationTemplate: '📦 **Nova Encomenda!**\n\n**Cliente:** {customerName}\n**Item:** {quantity}x {item}\n**Notas:** {notes}\n\nUse os botões abaixo para aceitar ou rejeitar.',
            channelNotificationTemplate: '📦 **Nova Encomenda**\n\n**De:** {customerName}\n**Para:** {supplierName}\n**Firma:** {firmName}\n**Item:** {quantity}x {item}',
            noSuppliersAvailable: '❌ Não há fornecedores disponíveis para esta firma no momento.',
            orderLimitReached: '❌ Você atingiu o limite máximo de {limit} encomendas ativas.',
            cooldownActive: '⏱️ Você precisa aguardar {minutes} minutos antes de fazer outra encomenda.'
          },
          formDisplay: {
            title: '📦 Sistema de Encomendas',
            description: '**Bem-vindo ao Sistema de Encomendas!**\n\nAqui você pode fazer encomendas de itens para outros jogadores.\n\n**Como funciona:**\n• Escolha a firma/categoria\n• Selecione o fornecedor\n• Especifique o item e quantidade\n• Aguarde a confirmação\n\nClique no botão abaixo para começar.',
            embedColor: '#00FF00',
            button: {
              text: 'Fazer Encomenda',
              emoji: '📦',
              style: 'Primary'
            }
          },
          steps: {
            selectFirm: {
              embedTitle: 'Passo 1/3 - Selecione a Firma',
              embedDescription: 'Escolha a firma/categoria do item que deseja encomendar:',
              dropdownPlaceholder: 'Selecione uma firma...'
            },
            selectSupplier: {
              embedTitle: 'Passo 2/3 - Selecione o Fornecedor',
              embedDescription: 'Escolha quem irá fornecer o item:',
              dropdownPlaceholder: 'Selecione um fornecedor...'
            },
            orderDetails: {
              modalTitle: 'Passo 3/3 - Detalhes da Encomenda',
              itemLabel: 'Nome do Item',
              itemPlaceholder: 'Ex: Madeira, Ferro, Comida...',
              quantityLabel: 'Quantidade',
              quantityPlaceholder: 'Ex: 10, 50, 100...',
              notesLabel: 'Observações (Opcional)',
              notesPlaceholder: 'Informações adicionais sobre a encomenda...'
            }
          }
        };
      } else {
        // Update existing config with new firms and orderChannelId
        config = {
          ...config,
          firms: autoGeneratedFirms,
          settings: {
            ...config.settings,
            orderChannelId: channel.id
          }
        };
      }

      // Save the config
      await OrdersService.updateConfig(guildId, config);

      // Create and send the order button embed
      const embed = new EmbedBuilder()
        .setTitle(config.formDisplay.title)
        .setDescription(config.formDisplay.description)
        .setColor(config.formDisplay.embedColor as any)
        .addFields(
          {
            name: '📊 Firmas Detectadas',
            value: autoGeneratedFirms
              .map(f => `• **${f.name}** → <#${f.id}>`)
              .join('\n'),
            inline: false
          },
          {
            name: '📋 Regras',
            value: [
              `• Máximo de **${config.settings.maxActiveOrdersPerUser}** encomendas ativas por usuário`,
              config.settings.orderCooldownMinutes > 0
                ? `• Tempo de espera entre encomendas: **${config.settings.orderCooldownMinutes} minutos**`
                : '• Sem tempo de espera entre encomendas',
              config.settings.requireApproval
                ? '• ✅ Encomendas precisam de aprovação'
                : '• ⚡ Encomendas são processadas automaticamente'
            ].join('\n'),
            inline: false
          }
        )
        .setFooter({ text: 'Sistema de Encomendas • Clique no botão abaixo para fazer uma encomenda' })
        .setTimestamp();

      const button = new ButtonBuilder()
        .setCustomId('order_start')
        .setLabel(config.formDisplay.button.text)
        .setEmoji(config.formDisplay.button.emoji)
        .setStyle(getButtonStyle(config.formDisplay.button.style));

      const row = new ActionRowBuilder<ButtonBuilder>()
        .addComponents(button);

      await channel.send({
        embeds: [embed],
        components: [row]
      });

      const successEmbed = new EmbedBuilder()
        .setTitle('✅ Sistema de Encomendas Configurado Automaticamente')
        .setColor('#00FF00')
        .setDescription(`O sistema detectou e configurou **${autoGeneratedFirms.length}** firma(s) automaticamente!`)
        .addFields(
          { name: '📁 Categoria', value: category.name, inline: true },
          { name: '📝 Canal de Encomendas', value: channel.toString(), inline: true },
          { name: '🏢 Firmas Configuradas', value: autoGeneratedFirms.length.toString(), inline: true },
          {
            name: '📊 Firmas Detectadas',
            value: autoGeneratedFirms.map(f => `• **${f.name}** (<#${f.id}>)`).join('\n'),
            inline: false
          },
          {
            name: 'ℹ️ Próximos Passos',
            value: '1. Configure fornecedores no painel web\n2. Os usuários podem começar a fazer encomendas\n3. As encomendas serão enviadas para os canais das firmas',
            inline: false
          }
        )
        .setTimestamp();

      await interaction.reply({
        embeds: [successEmbed],
        ephemeral: true
      });

    } catch (error) {
      console.error('Error setting up orders system:', error);
      await interaction.reply({
        content: '❌ Ocorreu um erro ao configurar o sistema de encomendas.',
        ephemeral: true
      });
    }
  }
};

function getButtonStyle(style: string): ButtonStyle {
  const styleMap: Record<string, ButtonStyle> = {
    'Primary': ButtonStyle.Primary,
    'Secondary': ButtonStyle.Secondary,
    'Success': ButtonStyle.Success,
    'Danger': ButtonStyle.Danger
  };
  return styleMap[style] || ButtonStyle.Primary;
}